# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20180404_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='gender',
            new_name='pet_type',
        ),
    ]
