# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20180404_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(),
        ),
    ]
